# Generated by Django 5.0.3 on 2024-06-21 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surver_officer', models.CharField(max_length=50)),
                ('surver_officer_name', models.CharField(max_length=100)),
                ('surver_officer_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(blank=True, default='', max_length=50)),
                ('main_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='serveyform.maincategory')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('legal_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('upload_media', models.ImageField(upload_to='static/assets/businessImages/')),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_number', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=1000)),
                ('mediclaim', models.CharField(max_length=50)),
                ('current_location', models.CharField(max_length=2000)),
                ('main_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='serveyform.maincategory')),
                ('sub_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='serveyform.subcategory')),
                ('survey_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serveyform.surveyofficer')),
            ],
        ),
    ]
