# Generated by Django 5.0.3 on 2024-06-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveyform', '0002_alter_subcategory_main_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyofficer',
            name='surver_officer',
        ),
        migrations.AlterField(
            model_name='surveyofficer',
            name='surver_officer_name',
            field=models.CharField(max_length=50),
        ),
    ]
