# Generated by Django 5.0.3 on 2024-06-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveyform', '0005_alter_surveyform_main_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyform',
            name='current_location',
            field=models.URLField(max_length=2000),
        ),
    ]
