# Generated by Django 5.0.3 on 2024-06-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveyform', '0006_alter_surveyform_current_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyform',
            name='current_location',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
