# Generated by Django 5.0.3 on 2024-06-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveyform', '0007_alter_surveyform_current_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyform',
            name='validate',
            field=models.BooleanField(default=False),
        ),
    ]
